In [74]:
import chess
import chess.engine as engine
import numpy as np
import random 
from copy import copy, deepcopy

board = chess.Board()
player_white = True
print(board)

r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R


In [87]:
white_pieces = ['P', 'N', 'B', 'R', 'Q', 'K']
black_pieces = [piece.lower() for piece in white_pieces]

board_ = np.ndarray.flatten(np.array(board.__str__().split()))
player = copy(board_)
opponent = copy(board_)
pawns = copy(board_)
knights = copy(board_)
rooks = copy(board_)
bishops = copy(board_)
queens = copy(board_)
kings = copy(board_)

if player_white:
    player = np.isin(player, white_pieces).astype(int)
    opponent = np.isin(player, black_pieces).astype(int)
else:
    player = np.isin(player, black_pieces).astype(int)
    opponent = np.isin(player, white_pieces).astype(int)
    
# player[63] = 1
print(player.reshape(8,8))
#     print(pp.symbol())
#     if pp is not None:

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1]]


In [86]:
if player_white:
    player_white = False
else:
    player_white = True
legal_moves = list(board.legal_moves)
move = str(random.choice(legal_moves))
board.push_uci(move)
board
print(board)

r n b q k b . r
p p p p p p p p
. . . . . . . n
. . . . . . . .
. . . . . . . .
. . . . . . . P
P P P P P P P .
R N B Q K B N R


In [15]:
engine = chess.engine.SimpleEngine.popen_uci("stockfish")
limit = chess.engine.Limit(time=2.0)
engine.play(board, limit)

AttributeError: module 'chess' has no attribute 'engine'